version: '3.1'
services:
  postgres:
    image: postgres:10.6
    ports:
    - 5432:5432
    environment:
    - POSTGRES_HOST=localhost
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=wedding
    volumes:
    - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql