spring:
  application.name: sladeandjessicawedding
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/wedding
    driver-class-name: org.postgresql.Driver
    tomcat:
      maxActive: 10
      maxIdle: 5
      minIdle: 1
      initialSize: 5